[tool.poetry]
version = "0.0.0"
name = "learning-python"
description = "learning-python"
authors = ["Adrian Macal <adma@amacal.pl>"]

[tool.poetry.scripts]
sso = "learning_python.main:sso"

[tool.poetry.dependencies]
python = ">=3.9.5,<3.12"
click = "8.1.3"
selenium = "4.8.3"
prompt-toolkit = "3.0.38"

[tool.poetry.group.dev.dependencies]
mypy = "1.2.0"

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"

[tool.mypy]
check_untyped_defs = true

[tool.black]
line-length = 119

[tool.pylint.messages_control]
disable = "C0114, C0115, C0116"
